name: Pull, Tag & Selenide Test

on:
  workflow_dispatch:            # manual trigger
  # push: [ "main" ]            # or on every push

jobs:
  pull_tag_test:
    runs-on: ubuntu-latest

    steps:
      ########################################################
      # 1) one Dock­er work: log in, pull, tag, start container  #
      ########################################################
      - uses: actions/checkout@v4

      - name: Pull base image
        run: docker pull alpine:3.20
      - name: Retag as my-image:latest
        run: docker tag alpine:3.20 my-image:latest

      - name: Run service container (background)
        # Port published on 8080; container is reachable as http://localhost:8080/
        run: |
          docker run -d --name myservice -p 8080:8080 my-image:latest
          echo "Waiting up to 30 s for server…"
          for i in {1..30}; do
            curl -fs http://localhost:8080/ || true
            if [ $? -eq 0 ]; then break; fi
            sleep 1
          done

      #####################################
      # 2) Java + Maven + Selenide tests  #
      #####################################
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Run Selenide smoke-test (headless Chrome)
        env:
          SELENIDE_BROWSER: chrome         # picked up by the test
          SELENIDE_HEADLESS: true
          TARGET_URL: http://myservice:8080/action
        run: mvn -B test
